"""Narration for the AI4S five-minute video. Cold open on the failure (scenario B, clean vs corrupted), then the idea,
the other scenarios, the evidence, the limits and the conclusion. Every number is from results/*.json or the live
dashboard.

Each line: (scene, spoken text for text-to-speech, caption shown in the subtitle band).
Numbers are spelled out in the spoken text so the voice reads them correctly; captions use digits.
"""
LINES = [
    # cold open: the failure
    ("cold", "Same patient. Same five models. One bad measurement.",
     "Same patient. Same five models. One bad measurement."),
    ("cold", "The thermometer reports Fahrenheit into a Celsius field. The sepsis risk goes from zero point nine percent to three point nine percent: a false alarm.",
     "The thermometer reports °F into a °C field. Sepsis risk goes from 0.9% to 3.9%: a false alarm."),
    ("cold", "All five models stay confident. A confidence check alone would let this alert through.",
     "All five models stay confident. A confidence check alone would let this alert through."),
    ("cold", "SepsisShield checks the inputs separately. Input trust falls to low, and the prediction is withheld.",
     "SepsisShield checks the inputs separately. Input trust falls to LOW, and the prediction is withheld."),
    # the idea
    ("idea", "Model uncertainty asks whether the models disagree. SepsisShield asks whether the data themselves deserve to be believed.",
     "Model uncertainty asks whether the models disagree. SepsisShield asks whether the data themselves deserve to be believed."),
    ("arch", "One path predicts sepsis risk, with calibrated LightGBM models and SHAP explanations.",
     "One path predicts sepsis risk, with calibrated LightGBM models and SHAP explanations."),
    ("arch", "A separate path checks whether the clinical inputs can be trusted.",
     "A separate path checks whether the clinical inputs can be trusted."),
    ("arch", "The decision layer shows the prediction, adds a warning, or withholds it. Only evidence from the inputs can withhold a prediction.",
     "The decision layer shows the prediction, adds a warning, or withholds it. Only evidence from the inputs can withhold."),
    # normal patients
    ("A", "Scenario A is a real patient from the held-out test set. The inputs are clean, trust is high, and the prediction is shown.",
     "Scenario A is a real patient from the held-out test set. The inputs are clean, trust is HIGH, and the prediction is shown."),
    ("A", "This patient's first alert came nine hours before onset.",
     "This patient's first alert came 9 hours before onset."),
    ("E", "In scenario E, risk jumps from one point one percent to thirteen point one percent,",
     "In scenario E, risk jumps from 1.1% to 13.1%,"),
    ("E", "and the alert is shown with high trust, eight hours before onset.",
     "and the alert is shown with HIGH trust, 8 hours before onset."),
    # back to the fault, then the harder cases
    ("B37", "Back to the fault from the opening. One hour later it is still inside the trend features, so trust is reduced and the screen says: verify inputs.",
     "Back to the fault from the opening. One hour later it is still inside the trend features: trust is REDUCED and the screen says VERIFY INPUTS."),
    ("C", "Scenario C is harder. A second patient's vitals are overwritten to look normal, and the model's real alert disappears: a confident all-clear.",
     "Scenario C is harder. A second patient's vitals are overwritten to look normal, and the model's real alert disappears: a confident all-clear."),
    ("C", "The models still agree. SepsisShield sees several vital signs normalising at once, and withholds the prediction instead of giving false reassurance.",
     "The models still agree. SepsisShield sees several vital signs normalising at once, and withholds the prediction instead of giving false reassurance."),
    ("F", "Scenario F shows the third state. The inputs pass every check, but the five models disagree more than on ninety-nine percent of validation hours.",
     "Scenario F shows the third state. The inputs pass every check, but the five models disagree more than on 99% of validation hours."),
    ("F", "Trust is reduced and the alert is shown with a warning. Disagreement alone never withholds, because there is no evidence against the inputs.",
     "Trust is REDUCED and the alert is shown with a warning. Disagreement alone never withholds, because there is no evidence against the inputs."),
    # evidence
    ("models", "On eight thousand and sixty-eight held-out patients, the model reaches an AUROC of zero point eight five two. XGBoost matches it, so the risk model is strong, but it is not the innovation.",
     "On 8,068 held-out patients, the model reaches an AUROC of 0.852. XGBoost matches it: the risk model is strong, but it is not the innovation."),
    ("models", "Fifty-three point nine percent of septic patients are alerted at least six hours before onset.",
     "53.9% of septic patients are alerted at least 6 hours before onset."),
    ("oper", "The alert threshold is a deployment choice. At the shipped three percent, seventy-nine point four percent of septic patients are alerted, with thirty-two point five new alert episodes per hundred non-septic patient-days. A site can trade sensitivity for fewer alerts.",
     "The alert threshold is a deployment choice. At the shipped 3%: 79.4% of septic patients alerted, 32.5 new alert episodes per 100 non-septic patient-days. A site can trade sensitivity for fewer alerts."),
    ("ablation", "The innovation shows up in the ablation. Across four simulated accidental fault types, faults flipped six thousand seven hundred and ninety alert decisions to a wrong answer.",
     "The innovation shows up in the ablation. Across 4 simulated accidental fault types, faults flipped 6,790 alert decisions to a wrong answer."),
    ("ablation", "The base model, the ensemble and calibration catch none of them. Ensemble disagreement catches four percent.",
     "The base model, the ensemble and calibration catch none of them. Ensemble disagreement catches 4%."),
    ("ablation", "Adding the input-integrity checks catches ninety-five point four percent, while withholding only zero point four six percent of clean patient-hours. A validation cohort replicates this at ninety-four point seven percent.",
     "Adding the input-integrity checks catches 95.4% (6,481 / 6,790), while withholding only 0.46% of clean patient-hours. Validation replication: 94.7%."),
    ("impossible", "Physiologically impossible values, like a heart rate of nine hundred, were withheld every time: one thousand two hundred and thirty-two out of one thousand two hundred and thirty-two.",
     "Physiologically impossible values, like a heart rate of 900, were withheld every time: 1,232 out of 1,232."),
    ("robust", "Under random missingness, accuracy degrades gradually. But missing data are not flagged, so the decisions they change are mostly silent. That is a limitation.",
     "Under random missingness, accuracy degrades gradually. But missing data are not flagged, so the decisions they change are mostly silent. That is a limitation."),
    ("why", "Every decision is explained in one panel: the top SHAP risk drivers, the integrity check that fired, the shift state, and the rule applied.",
     "Every decision is explained in one panel: the top SHAP risk drivers, the integrity check that fired, the shift state, and the rule applied."),
    # limits
    ("limits", "The limits matter. Deliberately edited inputs were caught only forty-two point five percent of the time, and twenty-six point five percent when the edits stay physiologically plausible.",
     "The limits matter. Deliberately edited inputs were caught only 42.5% of the time, and 26.5% when the edits stay physiologically plausible."),
    ("limits", "At a hospital the model never trained on, AUROC drops to zero point seven nine zero and zero point seven seven five. And all faults here are simulated.",
     "At a hospital the model never trained on, AUROC drops to 0.790 and 0.775. All faults here are simulated."),
    ("xsig", "We also tested a cross-signal consistency detector aimed at plausible edits. It did not meet the bar we set before testing, so it is reported, not shipped.",
     "We also tested a cross-signal consistency detector aimed at plausible edits. It did not meet the bar we set before testing, so it is reported, not shipped."),
    ("shift", "Scenario D shows an advisory signal: this patient's white cell count is far outside the training data. It never changes the decision.",
     "Scenario D shows an advisory signal: this patient's white cell count is far outside the training data. It never changes the decision."),
    ("impact", "SepsisShield is a research prototype, not a medical device, and not prospectively validated. The code, report and demo are public.",
     "SepsisShield is a research prototype, not a medical device, and not prospectively validated. Code, report and demo are public."),
    ("end", "SepsisShield does not only ask: what is this patient's risk? It also asks: can this prediction safely be trusted?",
     "SepsisShield does not only ask “What is this patient's risk?” It also asks “Can this prediction safely be trusted?”"),
]
