"""Narration for the ML Empowerment Build Challenge video (follows submission/ml_empowerment/VIDEO_PLAN.md).

Each line: (scene, spoken text for text-to-speech, caption shown in the subtitle band).
Numbers are spelled out in the spoken text so the voice reads them correctly; captions use digits.
"""
LINES = [
    ("problem", "Sepsis early-warning models are usually evaluated on how well they predict.",
     "Sepsis early-warning models are usually evaluated on how well they predict."),
    ("problem", "But what happens when the data going in are wrong? A thermometer in Fahrenheit, a frozen monitor, an edited chart.",
     "But what happens when the data going in are wrong? A thermometer in °F, a frozen monitor, an edited chart."),
    ("problem", "The model can still be confident.", "The model can still be confident."),
    ("arch", "SepsisShield separates two questions. The prediction path asks: how likely is sepsis?",
     "SepsisShield separates two questions. The prediction path asks: how likely is sepsis?"),
    ("arch", "Independent input-integrity checks ask: are these inputs believable?",
     "Independent input-integrity checks ask: are these inputs believable?"),
    ("arch", "A decision layer then shows the prediction, shows it with a warning, or withholds it until the data are checked.",
     "A decision layer then shows the prediction, shows it with a warning, or withholds it until the data are checked."),
    ("A", "Here is the live dashboard. Scenario A: a real, held-out patient.",
     "Here is the live dashboard. Scenario A: a real, held-out patient."),
    ("A", "Clean inputs, the five models agree, and input trust is high, so the prediction is shown.",
     "Clean inputs, the five models agree, and input trust is HIGH, so the prediction is shown."),
    ("A", "Its first alert came nine hours before the recorded onset, and the bars show what drove it.",
     "Its first alert came 9 hours before the recorded onset, and the bars show what drove it."),
    ("B", "Scenario B: the same patient, but the thermometer now reports Fahrenheit into a Celsius field.",
     "Scenario B: the same patient, but the thermometer now reports °F into a °C field."),
    ("B", "The risk jumps above the alert line: a false alarm.",
     "The risk jumps above the alert line: a false alarm."),
    ("B", "Model confidence still says confident. But input trust falls to low, a physiologically implausible temperature, and the prediction is withheld.",
     "Model confidence still says Confident. But input trust falls to LOW (a physiologically implausible temperature), and the prediction is withheld."),
    ("B37", "One hour later, trust is reduced: verify inputs.", "One hour later, trust is REDUCED: verify inputs."),
    ("C", "Scenario C: a second patient's vitals are overwritten to look normal, and the model's alert disappears.",
     "Scenario C: a second patient's vitals are overwritten to look normal, and the model's alert disappears."),
    ("C", "The models still agree. SepsisShield sees several vital signs normalising at once, and withholds the prediction instead of giving a silent all-clear.",
     "The models still agree. SepsisShield sees several vital signs normalising at once, and withholds the prediction instead of giving a silent all-clear."),
    ("evidence", "Does it hold up beyond three examples? On eight thousand and sixty-eight held-out patients, the model reaches an AUROC of zero point eight five two,",
     "Does it hold up beyond three examples? On 8,068 held-out patients, the model reaches an AUROC of 0.852,"),
    ("evidence", "and fifty-three point nine percent of septic patients are alerted at least six hours before onset.",
     "and 53.9% of septic patients are alerted at least 6 hours before onset."),
    ("evidence", "In a corruption benchmark, ninety-five point four percent of alert-changing wrong decisions caused by four simulated accidental fault types were flagged or withheld,",
     "In a corruption benchmark, 95.4% of alert-changing wrong decisions caused by 4 simulated accidental fault types were flagged or withheld (6,481 / 6,790),"),
    ("evidence", "while only zero point four six percent of clean patient-hours were withheld.",
     "while only 0.46% of clean patient-hours were withheld."),
    ("limits", "The limits matter too. Deliberately edited inputs were caught only forty-two point five percent of the time, and twenty-six point five percent when the edits stay realistic.",
     "The limits matter too. Deliberately edited inputs were caught only 42.5% of the time, and 26.5% when the edits stay realistic."),
    ("limits", "At a hospital the model never trained on, AUROC drops to zero point seven nine and zero point seven seven five.",
     "At a hospital the model never trained on, AUROC drops to 0.790 and 0.775."),
    ("shift", "A separate, advisory signal also warns when a patient looks unlike the training data. It is a caution, not proof that a prediction is wrong.",
     "A separate, advisory signal also warns when a patient looks unlike the training data. It is a caution, not proof that a prediction is wrong."),
    ("impact", "SepsisShield is a research prototype, not a medical device.",
     "SepsisShield is a research prototype, not a medical device."),
    ("end", "Its idea is simple: trust-aware AI should know not only when to predict, but when not to trust its inputs.",
     "Its idea is simple: trust-aware AI should know not only when to predict, but when not to trust its inputs."),
]
